// Mocks generated by Mockito 5.4.4 from annotations
// in example_flutter_hans/test/bloc/post/post_create_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:example_flutter_hans/data/client/post_client.dart' as _i2;
import 'package:example_flutter_hans/data/data_source/post_repository_impl.dart'
    as _i4;
import 'package:example_flutter_hans/data/models/post/post_model.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePostApiClient_0 extends _i1.SmartFake implements _i2.PostApiClient {
  _FakePostApiClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePostModel_1 extends _i1.SmartFake implements _i3.PostModel {
  _FakePostModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PostRepositoryImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostRepositoryImpl extends _i1.Mock
    implements _i4.PostRepositoryImpl {
  MockPostRepositoryImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PostApiClient get apiClient => (super.noSuchMethod(
        Invocation.getter(#apiClient),
        returnValue: _FakePostApiClient_0(
          this,
          Invocation.getter(#apiClient),
        ),
      ) as _i2.PostApiClient);

  @override
  _i5.Future<_i3.PostModel> addPost(_i3.PostModel? post) => (super.noSuchMethod(
        Invocation.method(
          #addPost,
          [post],
        ),
        returnValue: _i5.Future<_i3.PostModel>.value(_FakePostModel_1(
          this,
          Invocation.method(
            #addPost,
            [post],
          ),
        )),
      ) as _i5.Future<_i3.PostModel>);

  @override
  _i5.Future<List<_i3.PostModel>> getPosts() => (super.noSuchMethod(
        Invocation.method(
          #getPosts,
          [],
        ),
        returnValue: _i5.Future<List<_i3.PostModel>>.value(<_i3.PostModel>[]),
      ) as _i5.Future<List<_i3.PostModel>>);
}
